name: app_message
description: "A new Flutter package project."
version: 1.0.0
homepage: https://dannynguyen.vn/packages
repository: https://github.com/haidang93/app_message.git

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
